id: AE9DE174E
title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:22:15.229736
  last_modified_at: 2022-03-01 01:22:15.229743
