id: AE9DE174E
title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:22:15.242786
  last_modified_at: 2022-03-01 01:22:15.242790
