id: AE9DE174E
title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:22:15.252726
  last_modified_at: 2022-03-01 01:22:15.252729
