id: AE9DE174E
title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously Fulfills
  All Wishes (Sampa Lhundrupma)
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:22:15.260359
  last_modified_at: 2022-03-01 01:22:15.260363
