id: AE9DE174E
title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection that
  Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:22:15.265696
  last_modified_at: 2022-03-01 01:22:15.265698
